# Generated by Django 6.0.2 on 2026-02-24 19:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='planning', max_length=20)),
                ('start_location_name', models.CharField(blank=True, default='', max_length=255)),
                ('start_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('start_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('end_location_name', models.CharField(blank=True, default='', max_length=255)),
                ('end_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('end_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'trips',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('planned_arrival', models.DateTimeField(blank=True, null=True)),
                ('planned_departure', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trip_stops',
                'ordering': ['order'],
            },
        ),
    ]
