# Generated by Django 6.0.2 on 2026-02-24 19:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 currency code.', max_length=3)),
                ('is_settled', models.BooleanField(db_index=True, default=False)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'debts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 currency code.', max_length=3)),
                ('category', models.CharField(choices=[('food', 'Food & Drinks'), ('transport', 'Transport'), ('accommodation', 'Accommodation'), ('activity', 'Activity'), ('shopping', 'Shopping'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('split_type', models.CharField(choices=[('equal', 'Equal'), ('percentage', 'Percentage'), ('exact', 'Exact Amount')], default='equal', max_length=20)),
                ('receipt_url', models.URLField(blank=True, default='', max_length=500)),
                ('notes', models.TextField(blank=True, default='')),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseSplit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount owed by this user in the expense currency.', max_digits=12)),
                ('amount_base', models.DecimalField(blank=True, decimal_places=2, help_text='Amount converted to the base/group currency.', max_digits=12, null=True)),
                ('base_currency', models.CharField(blank=True, default='', help_text='The base currency this was converted to.', max_length=3)),
            ],
            options={
                'db_table': 'expense_splits',
                'ordering': ['-created_at'],
            },
        ),
    ]
